# Generated by Django 3.2.8 on 2021-11-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_connectmodel_myimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='画像')),
            ],
        ),
        migrations.AlterField(
            model_name='connectmodel',
            name='myimage',
            field=models.ImageField(blank=True, upload_to='../media'),
        ),
    ]
