# Generated by Django 3.2.8 on 2021-11-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_auto_20211105_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectmodel',
            name='myimage',
            field=models.ImageField(blank=True, upload_to='./media'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='画像'),
        ),
    ]
