# Generated by Django 3.2.8 on 2021-11-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_auto_20211105_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterField(
            model_name='connectmodel',
            name='myimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
