# Generated by Django 3.2.8 on 2021-11-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_connectmodel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectmodel',
            name='level_b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
    ]
