# Generated by Django 3.2.8 on 2021-11-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_auto_20211106_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='自分の名前'),
        ),
    ]
